using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CRDT.WF.Response
{
    public class ChangeCustomerDataReq
    {
        public string I_ZNUM { get; set; }
        public string I_ZSOURCE { get; set; }
        public string I_ZZMODIFYBY { get; set; }
        public string I_TEST { get; set; }
        public List<IT_CUST_CHANGE_DATA> IT_CUST_CHANGE_DATA { get; set; }
        public List<IT_CUST_CHANGE_DATA_X> IT_CUST_CHANGE_DATA_X { get; set; }
        public List<IT_CUST_VISITMASTER_DATA> IT_CUST_VISITMASTER_DATA { get; set; }
    }
    public class IT_CUST_CHANGE_DATA
    {
        public string ZPFLAG { get; set; }
        public string BU_GROUP { get; set; }
        public string KUNNR { get; set; }
        public string BUKRS { get; set; }
        public string BU_SORT1 { get; set; }
        public string BU_SORT2 { get; set; }
        public string NAME_ORG1 { get; set; }
        public string NAME_ORG2 { get; set; }
        public string STREET_SEN { get; set; }
        public string STR_SUPPL3_SEN { get; set; }
        public string LOCATION_SEN { get; set; }
        public string NAME1_SZF { get; set; }
        public string NAME2_SZF { get; set; }
        public string STREET_SZF { get; set; }
        public string STR_SUPPL3_SZF { get; set; }
        public string LOCATION_SZF { get; set; }
        public string STR_SUPPL3_SA { get; set; }
        public string LOCATION_SA { get; set; }
        public string POST_CODE1_SEN { get; set; }
        public string CITY1_SEN { get; set; }
        public string COUNTRY_SEN { get; set; }
        public string ROOMNUMBER_DEN { get; set; }
        public string FLOOR_DEN { get; set; }
        public string NAME_CO_DEN { get; set; }
        public string STR_SUPPL1_DEN { get; set; }
        public string STR_SUPPL2_DEN { get; set; }
        public string STREET_DEN { get; set; }
        public string STR_SUPPL3_DEN { get; set; }
        public string LOCATION_DEN { get; set; }
        public string CITY2_DEN { get; set; }
        public string ROOMNUMBER_DZF { get; set; }
        public string FLOOR_DZF { get; set; }
        public string NAME_CO_DZF { get; set; }
        public string STR_SUPPL1_DZF { get; set; }
        public string STR_SUPPL2_DZF { get; set; }
        public string STREET_DZF { get; set; }
        public string STR_SUPPL3_DZF { get; set; }
        public string LOCATION_DZF { get; set; }
        public string CITY2_DZF { get; set; }
        public string NAME1_CEN { get; set; }
        public string STREET_CEN { get; set; }
        public string STR_SUPPL3_CEN { get; set; }
        public string LOCATION_CEN { get; set; }
        public string NAME1_CZF { get; set; }
        public string STREET_CZF { get; set; }
        public string STR_SUPPL3_CZF { get; set; }
        public string LOCATION_CZF { get; set; }
        public string LANGU_CZF { get; set; }
        public string FAX_NUMBER_CZF { get; set; }
        public string BU_BKVID { get; set; }
        public string BU_BANKS { get; set; }
        public string BU_BANKK { get; set; }
        public string BU_BANKN { get; set; }
        public string BU_BKEXT { get; set; }
        public string BU_BKVID_N { get; set; }
        public string BU_BANKS_N { get; set; }
        public string BU_BANKK_N { get; set; }
        public string BU_BANKN_N { get; set; }
        public string VKORG { get; set; }
        public string VTWEG { get; set; }
        public string SPART { get; set; }
        public string BZIRK { get; set; }
        public string VKBUR { get; set; }
        public string WAERS { get; set; }
        public string KALKS { get; set; }
        public string LPRIO { get; set; }
        public string VWERK { get; set; }
        public string VSBED { get; set; }
        public string ZTERM_KNVV { get; set; }
        public string KTGRD { get; set; }
        public string TAXKD { get; set; }
        public string ZSHIPTO { get; set; }
        public string ZBILLTO { get; set; }
        public string ZPAYER { get; set; }
        public string AKONT { get; set; }
        public string ZTERM_KNB1 { get; set; }
        public string ZWELS { get; set; }
        public string ZUAWA { get; set; }
        public string KATR1 { get; set; }
        public string ZZCUSTTYPE { get; set; }
        public string ZZCUSTSTATUS { get; set; }
        public string ZZCLOSEDDATE { get; set; }
        public string ZZCLOSEDREASON { get; set; }
        public string ZZREOPENDATE { get; set; }
        public string ZZDELTYPE { get; set; }
        public string ZZKACODE { get; set; }
        public string ZZLONGITUDE { get; set; }
        public string ZZLATITUDE { get; set; }
        public string KATR2 { get; set; }
        public string ZZCUSTORGTYPE { get; set; }
        public string TYPE { get; set; }
        public string INSTITUTE { get; set; }
        public string IDNUMBER { get; set; }
        public string VALID_DATE_FROM { get; set; }
        public string VALID_DATE_TO { get; set; }
        public string ZZBANKGUREXPDATE { get; set; }
        public string ZZCRMANAGER { get; set; }
        public string ZZCHANNEL { get; set; }
        public string ZZSUBCHANNEL { get; set; }
        public string KVGR1 { get; set; }
        public string KVGR2 { get; set; }
        public string ZZSALESADMIN { get; set; }
        public string ZZRECONPRT { get; set; }
        public string ZZPS_ROUTE { get; set; }
        public string ZZMAINTAREA { get; set; }
        public string ZZMAINTOFFICE { get; set; }
        public string ZZSHIPPOINT { get; set; }
        public string ZZSHIPTYPE { get; set; }
        public string ZZTURNKEY { get; set; }
        public string ZZKOSTL { get; set; }
        public string ZZINVPRTTYP { get; set; }
        public string ZZDELPRTTYP { get; set; }
        public string ZZVSCUST { get; set; }
        public string ZZAP_FLAG { get; set; }
        public string ZZMATTYPE { get; set; }
        public string ZZZEROSALES { get; set; }
        public string ZZMAILADDR1 { get; set; }
        public string ZZMAILADDR2 { get; set; }
        public string ZZMAILADDR3 { get; set; }
        public string ZZTEXTCSS { get; set; }
        public string ZZTEXTSFA { get; set; }
        public string ZZTEXTDN { get; set; }
        public string ZZDNCOPY { get; set; }
        public string ZZDROUTE { get; set; }
        public string ZZDSMESSAGE1 { get; set; }
        public string ZZDSMESSAGE2 { get; set; }
        public string ZZDSMESSAGE3 { get; set; }
        public string ZZDSMESSAGE4 { get; set; }
        public string ZZCONTACTP09 { get; set; }
        public string ZZCONTACTT09 { get; set; }
        public string ZZCONTACTT09B { get; set; }
        public string ZZFMAILADDR1 { get; set; }
        public string ZZFMAILADDR2 { get; set; }
        public string ZZFMAILADDR3 { get; set; }
        public string ZZCONTACTT11 { get; set; }
        public string ZZCONTACTS10 { get; set; }
        public string ZZCONTACTP10 { get; set; }
        public string ZZCONTACTR10 { get; set; }
        public string ZZCONTACTT10 { get; set; }
        public string ZZCONTACTO10 { get; set; }
        public string ZZCONTACTE10 { get; set; }
        public string ZZCONTACTS12 { get; set; }
        public string ZZCONTACTP12 { get; set; }
        public string ZZCONTACTR12 { get; set; }
        public string ZZCONTACTT12 { get; set; }
        public string ZZCONTACTO12 { get; set; }
        public string ZZCONTACTE12 { get; set; }
        public string ZDELMON { get; set; }
        public string ZDELTUE { get; set; }
        public string ZDELWED { get; set; }
        public string ZDELTHU { get; set; }
        public string ZDELFRI { get; set; }
        public string ZDELSAT { get; set; }
        public string ZDELSUN { get; set; }
        public string ZDELWILL { get; set; }
        public string ZTIME1_FROM { get; set; }
        public string ZTIME1_TO { get; set; }
        public string ZTIME2_FROM { get; set; }
        public string ZTIME2_TO { get; set; }
        public string ZDELMON2 { get; set; }
        public string ZDELTUE2 { get; set; }
        public string ZDELWED2 { get; set; }
        public string ZDELTHU2 { get; set; }
        public string ZDELFRI2 { get; set; }
        public string ZDELSAT2 { get; set; }
        public string ZDELSUN2 { get; set; }
        public string ZDELWILL2 { get; set; }
        public string ZZDROUTE2 { get; set; }
        public string ZZCROSSSELL { get; set; }
        public string ZZCROSSEFFDATE { get; set; }
        public string KVGR3 { get; set; }
        public string KVGR4 { get; set; }
        public string ZZCUSTSEGMENT { get; set; }
        public string ZZDIFFLEVEL { get; set; }
        public string ZZNUMFLOOR { get; set; }
        public string ZZSTAIRFEE { get; set; }
        public string ZZDELSURCHAGE { get; set; }
        public string ZZDISPLAYPRICE { get; set; }
        public string AUFSD { get; set; }
        public string ZZNOOFSEAT { get; set; }
        public string ZZONLINECUST { get; set; }
        public string RULE_INDEX_FR { get; set; }
        public string RULE_INDEX_TO { get; set; }
        public string ZZOPENHR { get; set; }
        public string ZZCLOSEHR { get; set; }
        public string ZZLUNCHHR { get; set; }
        public string ZZTRUCKLIMIT { get; set; }
        public string ZZRESTPERMIT { get; set; }
        public string ZZSIGNMOD { get; set; }
        public string ZZPRICHFLEX { get; set; }
        public string ZZPROCHFLEX { get; set; }
        public string ZZNSEAPRD { get; set; }
        public string ZZMEDIAUSE { get; set; }
        public string ZZMULTMACHGRP { get; set; }
        public string ZZPRICEGRP { get; set; }
        public string ZZCUSTGRP { get; set; }
        public string ZZAGREEMENTTYPE { get; set; }
        public string ZZCONTRACTFROM { get; set; }
        public string ZZCONTRACTTO { get; set; }
        public string ZZSCHPOLICY { get; set; }
        public string ZZOPSREMARKS { get; set; }
        public string ZZVENDORTYPE { get; set; }
        public string ZZCHANNELSPEC { get; set; }
        public string ZZLINKEDVENDOR { get; set; }
        public string ZZLOCATIONVENDOR { get; set; }
        public string ZZDISTANCEOFINT { get; set; }
        public string ZZELECALH { get; set; }
        public string ZZSITE { get; set; }
        public string ZZSTAIRUPDOWN { get; set; }
        public string ZZSLOPEUPDOWN { get; set; }
        public string ZZSLOPEDISTANCE { get; set; }
        public string ZZNOOFSTAIR { get; set; }
        public string ZZNEEDSMLTRUCK { get; set; }
        public string ZZMOUNTED { get; set; }
        public string ZZCANOPY { get; set; }
        public string ZZNOOFSTAFF { get; set; }
        public string ZZACCTSTATUS { get; set; }
        public string ZZFSVBEVCOMPT { get; set; }
        public string ZZCOMPETITOR { get; set; }
        public string ZZNOOFCOMPT { get; set; }
        public string ZZSALESOFVOLUME { get; set; }
        public string ZZCUSTOMERREP { get; set; }
        public string ZZEDN { get; set; }
        public string SMTP_ADDR_DMS1 { get; set; }
        public string SMTP_ADDR_DMS2 { get; set; }
        public string ZZTOKENID { get; set; }
        public string CCNUM_CR { get; set; }
        public string DATBI_CR { get; set; }
        public string ZZWATERINSNUM { get; set; }
        public string ZZPOSTMIXOUTLET { get; set; }
        public string ZZDADROUTE { get; set; }
        public string ZZDLVATTRIBUTE { get; set; }
        public string ZZEREGDATE { get; set; }
        public string ZZELECAVA { get; set; }
        public string ZZELEPOTY { get; set; }
        public string ZZOPENDATE { get; set; }
        public string VISITMASTER { get; set; }
        public string ZFIELD02 { get; set; }
        public string ZFIELD03 { get; set; }
        public string ZFIELD04 { get; set; }
        public string ZFIELD05 { get; set; }
        public string ZFIELD06 { get; set; }
        public string ZFIELD07 { get; set; }
        public string ZFIELD08 { get; set; }
        public string ZFIELD09 { get; set; }
        public string ZFIELD10 { get; set; }
        public string PERFK { get; set; }
        public string PERRL { get; set; }
        public string ZZCUSTSEGMENT2 { get; set; }
        public string KOINH { get; set; }
        public string ACCNAME { get; set; }
    }
    public class IT_CUST_CHANGE_DATA_X
    {
        public string KUNNR { get; set; }
        public string BUKRS { get; set; }
        public string BU_SORT1 { get; set; }
        public string BU_SORT2 { get; set; }
        public string NAME_ORG1 { get; set; }
        public string NAME_ORG2 { get; set; }
        public string STREET_SEN { get; set; }
        public string STR_SUPPL3_SEN { get; set; }
        public string LOCATION_SEN { get; set; }
        public string NAME1_SZF { get; set; }
        public string NAME2_SZF { get; set; }
        public string STREET_SZF { get; set; }
        public string STR_SUPPL3_SZF { get; set; }
        public string LOCATION_SZF { get; set; }
        public string STR_SUPPL3_SA { get; set; }
        public string LOCATION_SA { get; set; }
        public string POST_CODE1_SEN { get; set; }
        public string CITY1_SEN { get; set; }
        public string COUNTRY_SEN { get; set; }
        public string ROOMNUMBER_DEN { get; set; }
        public string FLOOR_DEN { get; set; }
        public string NAME_CO_DEN { get; set; }
        public string STR_SUPPL1_DEN { get; set; }
        public string STR_SUPPL2_DEN { get; set; }
        public string STREET_DEN { get; set; }
        public string STR_SUPPL3_DEN { get; set; }
        public string LOCATION_DEN { get; set; }
        public string CITY2_DEN { get; set; }
        public string ROOMNUMBER_DZF { get; set; }
        public string FLOOR_DZF { get; set; }
        public string NAME_CO_DZF { get; set; }
        public string STR_SUPPL1_DZF { get; set; }
        public string STR_SUPPL2_DZF { get; set; }
        public string STREET_DZF { get; set; }
        public string STR_SUPPL3_DZF { get; set; }
        public string LOCATION_DZF { get; set; }
        public string CITY2_DZF { get; set; }
        public string NAME1_CEN { get; set; }
        public string STREET_CEN { get; set; }
        public string STR_SUPPL3_CEN { get; set; }
        public string LOCATION_CEN { get; set; }
        public string NAME1_CZF { get; set; }
        public string STREET_CZF { get; set; }
        public string STR_SUPPL3_CZF { get; set; }
        public string LOCATION_CZF { get; set; }
        public string LANGU_CZF { get; set; }
        public string FAX_NUMBER_CZF { get; set; }
        public string BU_BKVID { get; set; }
        public string BU_BANKS { get; set; }
        public string BU_BANKK { get; set; }
        public string BU_BANKN { get; set; }
        public string BU_BKEXT { get; set; }
        public string BU_BKVID_N { get; set; }
        public string BU_BANKS_N { get; set; }
        public string BU_BANKK_N { get; set; }
        public string BU_BANKN_N { get; set; }
        public string VKORG { get; set; }
        public string VTWEG { get; set; }
        public string SPART { get; set; }
        public string BZIRK { get; set; }
        public string VKBUR { get; set; }
        public string WAERS { get; set; }
        public string KALKS { get; set; }
        public string LPRIO { get; set; }
        public string VWERK { get; set; }
        public string VSBED { get; set; }
        public string ZTERM_KNVV { get; set; }
        public string KTGRD { get; set; }
        public string TAXKD { get; set; }
        public string ZSHIPTO { get; set; }
        public string ZBILLTO { get; set; }
        public string ZPAYER { get; set; }
        public string AKONT { get; set; }
        public string ZTERM_KNB1 { get; set; }
        public string ZWELS { get; set; }
        public string ZUAWA { get; set; }
        public string KATR1 { get; set; }
        public string ZZCUSTTYPE { get; set; }
        public string ZZCUSTSTATUS { get; set; }
        public string ZZCLOSEDDATE { get; set; }
        public string ZZCLOSEDREASON { get; set; }
        public string ZZREOPENDATE { get; set; }
        public string ZZDELTYPE { get; set; }
        public string ZZKACODE { get; set; }
        public string ZZLONGITUDE { get; set; }
        public string ZZLATITUDE { get; set; }
        public string KATR2 { get; set; }
        public string ZZCUSTORGTYPE { get; set; }
        public string TYPE { get; set; }
        public string INSTITUTE { get; set; }
        public string IDNUMBER { get; set; }
        public string VALID_DATE_FROM { get; set; }
        public string VALID_DATE_TO { get; set; }
        public string ZZBANKGUREXPDATE { get; set; }
        public string ZZCRMANAGER { get; set; }
        public string ZZCHANNEL { get; set; }
        public string ZZSUBCHANNEL { get; set; }
        public string KVGR1 { get; set; }
        public string KVGR2 { get; set; }
        public string ZZSALESADMIN { get; set; }
        public string ZZRECONPRT { get; set; }
        public string ZZPS_ROUTE { get; set; }
        public string ZZMAINTAREA { get; set; }
        public string ZZMAINTOFFICE { get; set; }
        public string ZZSHIPPOINT { get; set; }
        public string ZZSHIPTYPE { get; set; }
        public string ZZTURNKEY { get; set; }
        public string ZZKOSTL { get; set; }
        public string ZZINVPRTTYP { get; set; }
        public string ZZDELPRTTYP { get; set; }
        public string ZZVSCUST { get; set; }
        public string ZZAP_FLAG { get; set; }
        public string ZZMATTYPE { get; set; }
        public string ZZZEROSALES { get; set; }
        public string ZZMAILADDR1 { get; set; }
        public string ZZMAILADDR2 { get; set; }
        public string ZZMAILADDR3 { get; set; }
        public string ZZTEXTCSS { get; set; }
        public string ZZTEXTSFA { get; set; }
        public string ZZTEXTDN { get; set; }
        public string ZZDNCOPY { get; set; }
        public string ZZDROUTE { get; set; }
        public string ZZDSMESSAGE1 { get; set; }
        public string ZZDSMESSAGE2 { get; set; }
        public string ZZDSMESSAGE3 { get; set; }
        public string ZZDSMESSAGE4 { get; set; }
        public string ZZCONTACTP09 { get; set; }
        public string ZZCONTACTT09 { get; set; }
        public string ZZCONTACTT09B { get; set; }
        public string ZZFMAILADDR1 { get; set; }
        public string ZZFMAILADDR2 { get; set; }
        public string ZZFMAILADDR3 { get; set; }
        public string ZZCONTACTT11 { get; set; }
        public string ZZCONTACTS10 { get; set; }
        public string ZZCONTACTP10 { get; set; }
        public string ZZCONTACTR10 { get; set; }
        public string ZZCONTACTT10 { get; set; }
        public string ZZCONTACTO10 { get; set; }
        public string ZZCONTACTE10 { get; set; }
        public string ZZCONTACTS12 { get; set; }
        public string ZZCONTACTP12 { get; set; }
        public string ZZCONTACTR12 { get; set; }
        public string ZZCONTACTT12 { get; set; }
        public string ZZCONTACTO12 { get; set; }
        public string ZZCONTACTE12 { get; set; }
        public string ZDELMON { get; set; }
        public string ZDELTUE { get; set; }
        public string ZDELWED { get; set; }
        public string ZDELTHU { get; set; }
        public string ZDELFRI { get; set; }
        public string ZDELSAT { get; set; }
        public string ZDELSUN { get; set; }
        public string ZDELWILL { get; set; }
        public string ZTIME1_FROM { get; set; }
        public string ZTIME1_TO { get; set; }
        public string ZTIME2_FROM { get; set; }
        public string ZTIME2_TO { get; set; }
        public string ZDELMON2 { get; set; }
        public string ZDELTUE2 { get; set; }
        public string ZDELWED2 { get; set; }
        public string ZDELTHU2 { get; set; }
        public string ZDELFRI2 { get; set; }
        public string ZDELSAT2 { get; set; }
        public string ZDELSUN2 { get; set; }
        public string ZDELWILL2 { get; set; }
        public string ZZDROUTE2 { get; set; }
        public string ZZCROSSSELL { get; set; }
        public string ZZCROSSEFFDATE { get; set; }
        public string KVGR3 { get; set; }
        public string KVGR4 { get; set; }
        public string ZZCUSTSEGMENT { get; set; }
        public string ZZDIFFLEVEL { get; set; }
        public string ZZNUMFLOOR { get; set; }
        public string ZZSTAIRFEE { get; set; }
        public string ZZDELSURCHAGE { get; set; }
        public string ZZDISPLAYPRICE { get; set; }
        public string AUFSD { get; set; }
        public string ZZNOOFSEAT { get; set; }
        public string ZZONLINECUST { get; set; }
        public string RULE_INDEX_FR { get; set; }
        public string RULE_INDEX_TO { get; set; }
        public string ZZOPENHR { get; set; }
        public string ZZCLOSEHR { get; set; }
        public string ZZLUNCHHR { get; set; }
        public string ZZTRUCKLIMIT { get; set; }
        public string ZZRESTPERMIT { get; set; }
        public string ZZSIGNMOD { get; set; }
        public string ZZPRICHFLEX { get; set; }
        public string ZZPROCHFLEX { get; set; }
        public string ZZNSEAPRD { get; set; }
        public string ZZMEDIAUSE { get; set; }
        public string ZZMULTMACHGRP { get; set; }
        public string ZZPRICEGRP { get; set; }
        public string ZZCUSTGRP { get; set; }
        public string ZZAGREEMENTTYPE { get; set; }
        public string ZZCONTRACTFROM { get; set; }
        public string ZZCONTRACTTO { get; set; }
        public string ZZSCHPOLICY { get; set; }
        public string ZZOPSREMARKS { get; set; }
        public string ZZVENDORTYPE { get; set; }
        public string ZZCHANNELSPEC { get; set; }
        public string ZZLINKEDVENDOR { get; set; }
        public string ZZLOCATIONVENDOR { get; set; }
        public string ZZDISTANCEOFINT { get; set; }
        public string ZZELECALH { get; set; }
        public string ZZSITE { get; set; }
        public string ZZSTAIRUPDOWN { get; set; }
        public string ZZSLOPEUPDOWN { get; set; }
        public string ZZSLOPEDISTANCE { get; set; }
        public string ZZNOOFSTAIR { get; set; }
        public string ZZNEEDSMLTRUCK { get; set; }
        public string ZZMOUNTED { get; set; }
        public string ZZCANOPY { get; set; }
        public string ZZNOOFSTAFF { get; set; }
        public string ZZACCTSTATUS { get; set; }
        public string ZZFSVBEVCOMPT { get; set; }
        public string ZZCOMPETITOR { get; set; }
        public string ZZNOOFCOMPT { get; set; }
        public string ZZSALESOFVOLUME { get; set; }
        public string ZZCUSTOMERREP { get; set; }
        public string ZZEDN { get; set; }
        public string SMTP_ADDR_DMS1 { get; set; }
        public string SMTP_ADDR_DMS2 { get; set; }
        public string ZZTOKENID { get; set; }
        public string CCNUM_CR { get; set; }
        public string DATBI_CR { get; set; }
        public string ZZWATERINSNUM { get; set; }
        public string ZZPOSTMIXOUTLET { get; set; }
        public string ZZDADROUTE { get; set; }
        public string ZZDLVATTRIBUTE { get; set; }
        public string ZZEREGDATE { get; set; }
        public string ZZELECAVA { get; set; }
        public string ZZELEPOTY { get; set; }
        public string ZZOPENDATE { get; set; }
        public string VISITMASTER { get; set; }
        public string ZFIELD02 { get; set; }
        public string ZFIELD03 { get; set; }
        public string ZFIELD04 { get; set; }
        public string ZFIELD05 { get; set; }
        public string ZFIELD06 { get; set; }
        public string ZFIELD07 { get; set; }
        public string ZFIELD08 { get; set; }
        public string ZFIELD09 { get; set; }
        public string ZFIELD10 { get; set; }
        public string PERFK { get; set; }
        public string PERRL { get; set; }
        public string ZZCUSTSEGMENT2 { get; set; }
        public string KOINH { get; set; }
        public string ACCNAME { get; set; }
    }
    public class IT_CUST_VISITMASTER_DATA
    {
        public string KUNNR { get; set; }
        public string BUKRS { get; set; }
        public string VICAT { get; set; }
        public string SEQNR { get; set; }
        public string VIROUTE { get; set; }
        public string VIFEQ { get; set; }
        public DateTime VIFDATE { get; set; }
        public string VIWEEK { get; set; }
    }
}
